### ISSUE TITLE
Sending Antiforgerytoken with FromBody Attribute Web API

### ISSUE THREAD

**Issue by aboah** [plbonneville/blog-examples#1]
Dear Bonneville,
I am very grateful for your article (https://plbonneville.com/blog/sending-an-anti-forgery-token-with-asp.net-core-mvc-ajax-requests/)

However, I have tried sending antiforgerytoken with FromBody attribute that gives me error - partial json formatting failed.
when I take out the ValidateAntiforgerytoken attribute, it works.
Do you mind to cross check your code in Vs Studio 2019 dotnet 5.0 version.

**Comment by plbonneville** [comment]
Hi @aboah,

I've updated the [blog post](https://plbonneville.com/blog/sending-an-anti-forgery-token-with-asp.net-core-mvc-ajax-requests/) and the code sample here on GitHub to bring them to .NET 5.0.

Further, I've tested with Visual Studio 2019 and everything should now work as intended.

Hope this helps.
